export const ERROR = 'SH/LOGIN/ERROR';
export const LOADING = 'SH/LOGIN/LOADING';

export const ENTER_PHONE_NUMBER = 'SH/LOGIN/ENTER_PHONE_NUMBER';
export const OTP_LOGIN_ENTER_PHONE_NUMBER =
  'SH/LOGIN/OTP_LOGIN_ENTER_PHONE_NUMBER';

export const FORGET_PASSWORD_ENTER_PHONE_NUMBER =
  'SH/LOGIN/ FORGET_PASSWORD_ENTER_PHONE_NUMBER';

export const REGISTER_CONFORMATION_CODE = 'SH/LOGIN/REGISTER_CONFORMATION_CODE';
export const OTP_LOGIN_CONFORMATION_CODE =
  'SH/LOGIN/OTP_LOGIN_CONFORMATION_CODE';
export const FORGET_PASSWORD_CONFIRMATION_CODE =
  'SH/LOGIN/FORGET_PASSWORD_CONFIRMATION_CODE';

export const REGISTER_SET_NEW_PASSWORD = 'SH/LOGIN/REGISTER_SET_NEW_PASSWORD';
export const FORGET_SET_NEW_PASSWORD = 'SH/LOGIN/FORGET_SET_NEW_PASSWORD';

export const LOGIN_ASK_PASSWORD = 'SH/LOGIN/LOGIN_ASK_PASSWORD';

export const UPDATE_STEP = 'SH/LOGIN/UPDATE_STEP';
