export const ERROR_REGISTER_STEP_ONE = 'SH/Login/ERROR_REGISTER_STEP_ONE';
export const LOADING_REGISTER_STEP_ONE = 'SH/Login/LOADING_REGISTER_STEP_ONE';

export const GET_REGISTER_STEP_ONE = 'SH/Login/GET_REGISTER_STEP_ONE';

export const UPDATE_REGISTER_STEP_ONE = 'SH/Login/UPDATE_REGISTER_STEP_ONE';

export const UPDATE_SHOULD_SHOW_LOGIN = 'SH/Login/UPDATE_SHOULD_SHOW_LOGIN';
export const UPDATE_SHOULD_SHOW_REGISTER =
  'SH/REGISTER/UPDATE_SHOULD_SHOW_LOGIN';
