//MOVIE SERACH
export const ERROR_MOVIES = 'SH/SearchPage/ERROR_MOVIES';
export const LOADING_MOVIES = 'SH/SearchPage/LOADING_MOVIES';

export const GET_MOVIES_SEARCHPAGE = 'SH/SearchPage/GET_MOVIES_SEARCHPAGE';
export const UPDATE_MOVIES_SEARCHPAGE ='SH/SearchPage/UPDATE_MOVIES_SEARCHPAGE';
export const RESET_MOVIES_SEARCHPAGE = 'SH/SearchPage/RESET_MOVIES_SEARCHPAGE';

//SERIES SEARCH
export const ERROR_SERIES = 'SH/SearchPage/ERROR_SERIES';
export const LOADING_SERIES = 'SH/SearchPage/LOADING_SERIES';

export const GET_SERIES_SEARCHPAGE = 'SH/SearchPage/GET_SERIES_SEARCHPAGE';
export const UPDATE_SERIES_SEARCHPAGE ='SH/SearchPage/UPDATE_SERIES_SEARCHPAGE';
export const RESET_SERIES_SEARCHPAGE = 'SH/SearchPage/RESET_SERIES_SEARCHPAGE';

//CASTS SERACH
export const ERROR_CASTS = 'SH/SearchPage/ERROR_CASTS';
export const LOADING_CASTS = 'SH/SearchPage/LOADING_CASTS';

export const GET_CASTS_SEARCHPAGE = 'SH/SearchPage/GET_CASTS_SEARCHPAGE';
export const UPADTE_CASTS_SEARCHPAGE = 'SH/SearchPage/UPADTE_CASTS_SEARCHPAGE';
export const RESET_CASTS_SEARCHPAGE = 'SH/SearchPage/RESET_CASTS_SEARCHPAGE';