const SORT_TYPES = {
  CREATED_DATA_DESC: 'CREATED_DATA_DESC',
  CREATED_DATA_ASC: ' CREATED_DATA_ASC',
  VISITED_COUNT_DESC: 'VISITED_COUNT_DESC',
  VISITED_COUNT_ASC: 'VISITED_COUNT_ASC',
  IMDB_RANK_DESC: ' IMDB_RANK_DESC',
  IMDB_RANK_ASC: 'IMDB_RANK_ASC',
};

export default SORT_TYPES;
