export const ERROR = 'SH/SeriesPage/ERROR';
export const LOADING = 'SH/SeriesPage/LOADING';
export const GET_SERIESPAGE = 'SH/SeriesPage/GET_SERIESPAGE';
export const UPDATE_SERIESPAGE = 'SH/SeriesPage/UPDATE_SERIESPAGE';
//awards series

export const ERROR_AWARDS = 'SH/SeriesPage/ERROR_AWARDS';
export const LOADING_AWARDS = 'SH/SeriesPage/LOADING_AWARDS';
export const GET_SERIESPAGE_AWARDS = 'SH/SeriesPage/GET_SERIESPAGE_AWARDS';
export const UPDATE_SERIESPAGE_AWARDS = 'SH/SeriesPage/UPDATE_SERIESPAGE_AWARDS';

//favaraite
export const ERROR_FAVARITE_SERIES = 'SH/SeriesPage/ERROR_FAVARITE_SERIES';
export const LOADING_FAVARITE_SERIES = 'SH/SeriesPage/LOADING_FAVARITE_SERIES';
export const GET_SERIESPAGE_FAVARITE = 'SH/SeriesPage/GET_SERIESPAGE_FAVARITE';
export const UPDATE_SERIESPAGE_FAVARITE = 'SH/SeriesPage/UPDATE_SERIESPAGE_FAVARITE';

//bookmark
export const ERROR_BOOKMARK_SERIES = 'SH/SeriesPage/ERROR_BOOKMARK_SERIES';
export const LOADING_BOOKMARK_SERIES = 'SH/SeriesPage/LOADING_BOOKMARK_SERIES';
export const GET_SERIESPAGE_BOOKMARK = 'SH/SeriesPage/GET_SERIESPAGE_BOOKMARK';
export const UPDATE_SERIESPAGE_BOOKMARK = 'SH/SeriesPage/UPDATE_SERIESPAGE_BOOKMARK';


//del bookmark
export const ERROR_BOOKMARK_SERIES_DEL = 'SH/SeriesPage/ERROR_BOOKMARK_SERIES_DEL';
export const LOADING_BOOKMARK_SERIES_DEL = 'SH/SeriesPage/LOADING_BOOKMARK_SERIES_DEL';
export const GET_SERIESPAGE_BOOKMARK_DEL = 'SH/SeriesPage/GET_SERIESPAGE_BOOKMARK_DEL';
export const UPDATE_SERIESPAGE_BOOKMARK_DEL = 'SH/SeriesPage/UPDATE_SERIESPAGE_BOOKMARK_DEL';