export const ERROR = 'SH/SeriesPage/ERROR';
export const LOADING = 'SH/SeriesPage/LOADING';
export const GET_SERIESPAGE = 'SH/SeriesPage/GET_SERIESPAGE';
export const UPDATE_SERIESPAGE = 'SH/SeriesPage/UPDATE_SERIESPAGE';
//awards series

export const ERROR_AWARDS = 'SH/SeriesPage/ERROR_AWARDS';
export const LOADING_AWARDS = 'SH/SeriesPage/LOADING_AWARDS';
export const GET_SERIESPAGE_AWARDS = 'SH/SeriesPage/GET_SERIESPAGE_AWARDS';
export const UPDATE_SERIESPAGE_AWARDS = 'SH/SeriesPage/UPDATE_SERIESPAGE_AWARDS';

//favaraite
export const ERROR_SERIES_RANK = 'SH/SeriesPage/ERROR_SERIES_RANK';
export const LOADING_SERIES_RANK = 'SH/SeriesPage/LOADING_SERIES_RANK';
export const UPDATE_SERIES_RANK = 'SH/SeriesPage/UPDATE_SERIES_RANK';
export const UPDATE_SERIES_RANK_REDUCER = 'SH/SeriesPage/UPDATE_SERIES_RANK_REDUCER';

//bookmark
export const ERROR_BOOKMARK_SERIES = 'SH/SeriesPage/ERROR_BOOKMARK_SERIES';
export const LOADING_BOOKMARK_SERIES = 'SH/SeriesPage/LOADING_BOOKMARK_SERIES';
export const GET_SERIESPAGE_BOOKMARK = 'SH/SeriesPage/GET_SERIESPAGE_BOOKMARK';
export const UPDATE_SERIESPAGE_BOOKMARK = 'SH/SeriesPage/UPDATE_SERIESPAGE_BOOKMARK';


//del bookmark
export const ERROR_BOOKMARK_SERIES_DEL = 'SH/SeriesPage/ERROR_BOOKMARK_SERIES_DEL';
export const LOADING_BOOKMARK_SERIES_DEL = 'SH/SeriesPage/LOADING_BOOKMARK_SERIES_DEL';
export const GET_SERIESPAGE_BOOKMARK_DEL = 'SH/SeriesPage/GET_SERIESPAGE_BOOKMARK_DEL';
export const UPDATE_SERIESPAGE_BOOKMARK_DEL = 'SH/SeriesPage/UPDATE_SERIESPAGE_BOOKMARK_DEL';

//cooment series

export const ERROR_SERIE_COMMENT = 'SH/SeriesPage/ERROR_SERIE_COMMENT';
export const LOADING_SERIE_COMMENT = 'SH/SeriesPage/LOADING_SERIE_COMMENT';

export const GET_COMMENT_SERIE = 'SH/SeriesPage/GET_COMMENT_SERIE';

export const UPDATE_COMMENT_SERIE = 'SH/SeriesPage/UPDATE_COMMENT_SERIE';
//set comment
export const ERROR_SERIES_COMMENT_SEND = 'SH/SeriesPage/ERROR_SERIES_COMMENT_SEND';
export const LOADING_SERIES_COMMENT_SEND = 'SH/SeriesPage/LOADING_SERIES_COMMENT_SEND';

export const SET_COMMENT_SERIES = 'SH/SeriesPage/SET_COMMENT_SERIES';

export const UPDATE_COMMENT_SERIES_SEND = 'SH/SeriesPage/UPDATE_COMMENT_SERIES_SEND';

//like movie
export const ERROR_SERIES_LIKE = 'SH/SeriesPage/ERROR_SERIES_LIKE';
export const LOADING_SERIES_LIKE = 'SH/SeriesPage/LOADING_SERIES_LIKE';
export const SET_SERIES_LIKE = 'SH/SeriesPage/SET_SERIES_LIKE';
export const UPDATE_SERIES_LIKE ='SH/SeriesPage/UPDATE_SERIES_LIKE';