export const ERROR = 'SH/MoviesPage/ERROR';
export const LOADING = 'SH/MoviesPage/LOADING';

export const GET_MOVIEPAGE = 'SH/MoviesPage/GET_MOVIEPAGE';

export const UPDATE_MOVIEPAGE = 'SH/MoviesPage/UPDATE_MOVIEPAGE';

//awardes movie

export const ERROR_MOVIE = 'SH/MoviesPage/ERROR_MOVIE';
export const LOADING_MOVIE = 'SH/MoviesPage/LOADING_MOVIE';

export const GET_AWARD_MOVIEPAGE = 'SH/MoviesPage/GET_AWARD_MOVIEPAGE';

export const UPDATE_AWARD_MOVIEPAGE = 'SH/MoviesPage/UPDATE_AWARD_MOVIEPAGE';

//favarite movie
export const ERROR_MOVIE_RANK = 'SH/MoviesPage/ERROR_MOVIE_RANK';
export const LOADING_MOVIE_RANK = 'SH/MoviesPage/LOADING_MOVIE_RANK';
export const UPDATE_MOVIE_RANK = 'SH/MoviesPage/UPDATE_MOVIE_RANK';
export const UPDATE_MOVIE_RANK_REDUCER =
  'SH/MoviesPage/UPDATE_MOVIE_RANK_REDUCER';

//add bookmark
export const ERROR_MOVIE_BOOKMARK = 'SH/MoviesPage/ERROR_MOVIE_BOOKMARK';
export const LOADING_MOVIE_BOOKMARK = 'SH/MoviesPage/LOADING_MOVIE_BOOKMARK';

export const GET_BOOKMARK_MOVIEPAGE = 'SH/MoviesPage/GET_BOOKMARK_MOVIEPAGE';

export const UPDATE_BOOKMARK_MOVIEPAGE =
  'SH/MoviesPage/UPDATE_BOOKMARK_MOVIEPAGE';

//delete bookmark
export const ERROR_MOVIE_BOOKMARK_DELET =
  'SH/MoviesPage/ERROR_MOVIE_BOOKMARK_DELET';
export const LOADING_MOVIE_BOOKMARK_DELET =
  'SH/MoviesPage/LOADING_MOVIE_BOOKMARK_DELET';

export const GET_BOOKMARK_MOVIEPAGE_DELET =
  'SH/MoviesPage/GET_BOOKMARK_MOVIEPAGE_DELET';

export const UPDATE_BOOKMARK_MOVIEPAGE_DELET =
  'SH/MoviesPage/UPDATE_BOOKMARK_MOVIEPAGE_DELET';
//commnet movie

export const ERROR_MOVIE_COMMENT = 'SH/MoviesPage/ERROR_MOVIE_COMMENT';
export const LOADING_MOVIE_COMMENT = 'SH/MoviesPage/LOADING_MOVIE_COMMENT';

export const GET_COMMENT_MOVIES = 'SH/MoviesPage/GET_COMMENT_MOVIES';

export const UPDATE_COMMENT_MOVIES = 'SH/MoviesPage/UPDATE_COMMENT_MOVIES';
//commnet send

export const ERROR_MOVIE_COMMENT_SEND =
  'SH/MoviesPage/ERROR_MOVIE_COMMENT_SEND';
export const LOADING_MOVIE_COMMENT_SEND =
  'SH/MoviesPage/LOADING_MOVIE_COMMENT_SEND';

export const SET_COMMENT_MOVIES = 'SH/MoviesPage/SET_COMMENT_MOVIES';

export const UPDATE_COMMENT_MOVIES_SEND =
  'SH/MoviesPage/UPDATE_COMMENT_MOVIES_SEND';

//like movie
export const ERROR_MOVIE_LIKE = 'SH/MoviesPage/ERROR_MOVIE_LIKE';
export const LOADING_MOVIE_LIKE = 'SH/MoviesPage/LOADING_MOVIE_LIKE';
export const SET_MOVIE_LIKE = 'SH/MoviesPage/SET_MOVIE_LIKE';
export const UPDATE_MOVIE_LIKE = 'SH/MoviesPage/UPDATE_MOVIE_LIKE';

//commnet reply send
export const ERROR_MOVIE_COMMENT_SEND_REPLY =
  'SH/MoviesPage/ERROR_MOVIE_COMMENT_SEND_REPLY';
export const LOADING_MOVIE_COMMENT_SEND_REPLY =
  'SH/MoviesPage/LOADING_MOVIE_COMMENT_SEND_REPLY';

export const SET_REPLY_COMMENT_MOVIES =
  'SH/MoviesPage/SET_REPLY_COMMENT_MOVIES';

export const UPDATE_COMMENT_MOVIES_SEND_REPLY =
  'SH/MoviesPage/UPDATE_COMMENT_MOVIES_SEND_REPLY';

//commnet movie  reply more

export const ERROR_MOVIE_COMMENT_REPLY_MORE =
  'SH/MoviesPage/ERROR_MOVIE_COMMENT_REPLY_MORE';
export const LOADING_MOVIE_COMMENT_REPLY_MORE =
  'SH/MoviesPage/LOADING_MOVIE_COMMENT_REPLY_MORE';

export const GET_COMMENT_MOVIES_REPLY_MORE =
  'SH/MoviesPage/GET_COMMENT_MOVIES_REPLY_MORE';

export const UPDATE_COMMENT_MOVIES_REPLY_MORE =
  'SH/MoviesPage/UPDATE_COMMENT_MOVIES_REPLY_MORE';

// comment reply like
export const ERROR_COMMENT_REPLY_LIKE =
  'SH/MoviesPage/ERROR_COMMENT_REPLY_LIKE';
export const LOADING_COMMENT_REPLY_LIKE =
  'SH/MoviesPage/LOADING_COMMENT_REPLY_LIKE';

export const GET_COMMENT_REPLY_LIKE = 'SH/MoviesPage/GET_COMMENT_REPLY_LIKE';

export const UPDATE_COMMENT_REPLY_LIKE =
  'SH/MoviesPage/UPDATE_COMMENT_REPLY_LIKE';
