//register step one

export const ERROR_REGISTER_STEP_ONE = 'SH/Login/ERROR_REGISTER_STEP_ONE';
export const LOADING_REGISTER_STEP_ONE = 'SH/Login/LOADING_REGISTER_STEP_ONE';

export const GET_REGISTER_STEP_ONE = 'SH/Login/GET_REGISTER_STEP_ONE';

export const UPDATE_REGISTER_STEP_ONE = 'SH/Login/UPDATE_REGISTER_STEP_ONE';

//register step three
export const ERROR_REGISTER_STEP_THREE = 'SH/Login/ERROR_REGISTER_STEP_THREE';
export const LOADING_REGISTER_STEP_THREE =
  'SH/Login/LOADING_REGISTER_STEP_THREE';

export const GET_REGISTER_STEP_THREE = 'SH/Login/GET_REGISTER_STEP_THREE';

export const UPDATE_REGISTER_STEP_THREE = 'SH/Login/UPDATE_REGISTER_STEP_THREE';

//CHECK NUMBER AND SHOW COMPONENT
export const UPDATE_SHOULD_SHOW_LOGIN = 'SH/Login/UPDATE_SHOULD_SHOW_LOGIN';
export const UPDATE_SHOULD_SHOW_REGISTER =
  'SH/REGISTER/UPDATE_SHOULD_SHOW_LOGIN';
export const UPDATE_SHOULD_SHOW_PASSWORD =
  'SH/PASSWORD/UPDATE_SHOUD_SHOW_PASSWORD';

//STEP LOGIN USER
export const ERROR_LOGIN = 'SH/Login/ERROR_LOGIN';
export const LOADING_LOGIN = 'SH/Login/LOADING_LOGIN';

export const GET_LOGIN = 'SH/Login/GET_LOGIN';

export const UPDATE_LOGIN = 'SH/Login/UPDATE_LOGIN';

//register step two
export const ERROR_CONFIRMATION_CODE = 'SH/Login/ERROR_CONFIRMATION_CODE';
export const LODING_CONFIRMATION_CODE = 'SH/Login/LODING_CONFIRMATION_CODE';

export const POST_CONFIRMATION_CODE = 'SH/Login/POST_CONFIRMATION_CODE';

export const UPDATE_CONFIRMATION_CODE = 'SH/Login/UPDATE_CONFIRMATION_CODE';
