export const GET_HOME_PAGE_REQUEST = 'SH/Junk/GET_HOME_PAGE_REQUEST';
export const GET_HOME_PAGE_SUCCESS = 'SH/Junk/GET_HOME_PAGE_SUCCESS';
export const GET_HOME_PAGE_FAILURE = 'SH/Junk/GET_HOME_PAGE_FAILURE';
